### PR TITLE
fix for daterangepicker and add internationalization

### PR DESCRIPTION
**Pull request by TomeCirun**

### CODE REVIEW

**Comment by BWibo** [comment]
This leads to this runtime error:

```
Traceback (most recent call last):
  File "/usr/local/bin/ckan", line 8, in <module>
    sys.exit(ckan())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/srv/app/src/ckan/ckan/cli/cli.py", line 116, in parse_args
    result = super(ExtendableGroup, self).parse_args(ctx, args)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1212, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1630, in handle_parse_result
    value = invoke_param_callback(self.callback, ctx, self, value)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 123, in invoke_param_callback
    return callback(ctx, param, value)
  File "/srv/app/src/ckan/ckan/cli/cli.py", line 126, in _init_ckan_config
    _add_ctx_object(ctx, value)
  File "/srv/app/src/ckan/ckan/cli/cli.py", line 135, in _add_ctx_object
    ctx.obj = CtxObject(path)
  File "/srv/app/src/ckan/ckan/cli/cli.py", line 57, in __init__
    self.app = make_app(self.config)
  File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
    load_environment(conf)
  File "/srv/app/src/ckan/ckan/config/environment.py", line 138, in load_environment
    build_js_translations()
  File "/srv/app/src/ckan/ckan/lib/i18n.py", line 379, in build_js_translations
    langs.update(plugin.i18n_locales())
  File "/srv/app/src/ckan/ckan/lib/plugins.py", line 617, in i18n_locales
    d in os.listdir(directory)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/ckanext/datesearch/i18n'
```

Looks like a dependency issue. Is `requirements.txt` up to date?

**Comment by TomeCirun** [comment]
> This leads to this runtime error:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/ckan", line 8, in <module>
>     sys.exit(ckan())
>   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 781, in main
>     with self.make_context(prog_name, args, **extra) as ctx:
>   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 700, in make_context
>     self.parse_args(ctx, args)
>   File "/srv/app/src/ckan/ckan/cli/cli.py", line 116, in parse_args
>     result = super(ExtendableGroup, self).parse_args(ctx, args)
>   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1212, in parse_args
>     rest = Command.parse_args(self, ctx, args)
>   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1048, in parse_args
>     value, args = param.handle_parse_result(ctx, opts, args)
>   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1630, in handle_parse_result
>     value = invoke_param_callback(self.callback, ctx, self, value)
>   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 123, in invoke_param_callback
>     return callback(ctx, param, value)
>   File "/srv/app/src/ckan/ckan/cli/cli.py", line 126, in _init_ckan_config
>     _add_ctx_object(ctx, value)
>   File "/srv/app/src/ckan/ckan/cli/cli.py", line 135, in _add_ctx_object
>     ctx.obj = CtxObject(path)
>   File "/srv/app/src/ckan/ckan/cli/cli.py", line 57, in __init__
>     self.app = make_app(self.config)
>   File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
>     load_environment(conf)
>   File "/srv/app/src/ckan/ckan/config/environment.py", line 138, in load_environment
>     build_js_translations()
>   File "/srv/app/src/ckan/ckan/lib/i18n.py", line 379, in build_js_translations
>     langs.update(plugin.i18n_locales())
>   File "/srv/app/src/ckan/ckan/lib/plugins.py", line 617, in i18n_locales
>     d in os.listdir(directory)
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/ckanext/datesearch/i18n'
> ```
> 
> Looks like a dependency issue. Is `requirements.txt` up to date?

the error says that you do not have a file inside  `ckanext/datesearch/ named i18n` @BWibo

**Comment by BWibo** [comment]
OK, @MarijaKnezevic: `Manifest` file?

**Review by BWibo — CHANGES_REQUESTED** [review]
When we want to include all files in theses folder, we should use:
`recursive-include ckanext/datesearch/i18n *`
See here: https://packaging.python.org/en/latest/guides/using-manifest-in/

**Pull request merged**
